import AuthProvider from "@/context/auth.js";
import Navbar from "../component/navbar/Navbar.jsx";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar/>
          {children}
          </AuthProvider>
      </body>
    </html>
  );
}
